version: '3.4'
services:
    web:
        build: .
        container_name: web
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ../code:/code
        networks:
            - python
        ports:
            - "8000:8000"
    
    pgsql:
        image: postgres:9.6-alpine
        container_name: pgsql
        environment:
            POSTGRES_PASSWORD: "12345678"
            PGDATA: "/var/lib/postgresql/data/pgdata"
        ports:
            - "5432:5432"
        volumes:
            - "dados-pg:/var/lib/postgresql/data/pgdata"
#            - "./bancos_iniciar:/docker-entrypoint-initdb.d"
        networks:
            - pgsql
            
    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: "diogocorazolla@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "123456"
        ports:
            - "8085:80"
        depends_on:
            - pgsql
        volumes:
            - "./pgadmin_config:/var/lib/pgadmin"
        networks:
            - pgsql
          
volumes:
    dados-pg:
        driver: local
        name: dados-pg
        
networks:
    pgsql:
        driver: bridge
    python:
        driver: bridge